
package sdx.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceSoap", targetNamespace = "http://tempuri.org/")
//@XmlSeeAlso({
//    ObjectFactory.class
//})
public interface ServiceSoap {


    /**
     * <b>校验用户信息是否正确</b><br/>返回：校验结果
     * 
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://tempuri.org/isValid")
    @WebResult(name = "isValidResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "isValid", targetNamespace = "http://tempuri.org/", className = "webdata.IsValid")
    @ResponseWrapper(localName = "isValidResponse", targetNamespace = "http://tempuri.org/", className = "webdata.IsValidResponse")
    public boolean isValid();

    /**
     * <b>获取节点实时数据</b><br/>nodeId - 节点编号<br/>返回：获取指定节点当前实时数据
     *
     * @param nodeId
     * @return
     *     returns webdata.ArrayOfEnvInfoDetail
     */
    @WebMethod(action = "http://tempuri.org/getEnvInfoDetails")
    @WebResult(name = "getEnvInfoDetailsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getEnvInfoDetails", targetNamespace = "http://tempuri.org/", className = "webdata.GetEnvInfoDetails")
    @ResponseWrapper(localName = "getEnvInfoDetailsResponse", targetNamespace = "http://tempuri.org/", className = "webdata.GetEnvInfoDetailsResponse")
    public ArrayOfEnvInfoDetail getEnvInfoDetails(
            @WebParam(name = "nodeId", targetNamespace = "http://tempuri.org/")
                    int nodeId);

    /**
     * <b>根据基地编号获取气象点数据</b><br/>regionId - 基地编号<br/>返回：获取指定基地气象点实时数据
     *
     * @param regionId
     * @return
     *     returns webdata.ArrayOfEnvInfoDetail
     */
    @WebMethod(action = "http://tempuri.org/getWeatherPointsByRegionId")
    @WebResult(name = "getWeatherPointsByRegionIdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getWeatherPointsByRegionId", targetNamespace = "http://tempuri.org/", className = "webdata.GetWeatherPointsByRegionId")
    @ResponseWrapper(localName = "getWeatherPointsByRegionIdResponse", targetNamespace = "http://tempuri.org/", className = "webdata.GetWeatherPointsByRegionIdResponse")
    public ArrayOfEnvInfoDetail getWeatherPointsByRegionId(
            @WebParam(name = "regionId", targetNamespace = "http://tempuri.org/")
                    int regionId);

    /**
     * <b>根据基地网关编码获取气象点数据</b><br/>bmId - 基地网关编码<br/>返回：获取指定基地气象点实时数据
     *
     * @param bmId
     * @return
     *     returns webdata.ArrayOfEnvInfoDetail
     */
    @WebMethod(action = "http://tempuri.org/getWeatherPointsByBMId")
    @WebResult(name = "getWeatherPointsByBMIdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getWeatherPointsByBMId", targetNamespace = "http://tempuri.org/", className = "webdata.GetWeatherPointsByBMId")
    @ResponseWrapper(localName = "getWeatherPointsByBMIdResponse", targetNamespace = "http://tempuri.org/", className = "webdata.GetWeatherPointsByBMIdResponse")
    public ArrayOfEnvInfoDetail getWeatherPointsByBMId(
            @WebParam(name = "bmId", targetNamespace = "http://tempuri.org/")
                    int bmId);



}
